### ISSUE TITLE
Some corrections for postgres-reactive

### ISSUE THREAD

**Issue by koji-k** [micronaut-projects/micronaut-docs#1]
# YAML
[Sample YAML for postgres-reactive](https://docs.micronaut.io/latest/guide/index.html#_configuring_the_reactive_postgres_client) is like a following now:

```yaml
postgres:
        reactive:
                port: 5432
                host: the-host
                database: the-db
                user: test
                password: test
                maxSize: 5
```

But, i think that must be like a following. so `client` is needed.:

```yaml
postgres:
    reactive:
        client:
            port: 5432
            host: the-host
            database: the-db
            user: test
            password: test
            maxSize: 5
```

# Dependencies
Document explains that `testCompile project(":configurations:postgres-reactive")` must be added into build.gradle.
I tried with that( with "compile project ..."), but i got following error.

```
[koji:kojisample]$ ./gradlew run

FAILURE: Build failed with an exception.

* Where:
Build file '/home/koji/IdeaProjects/kojisample/build.gradle' line: 49

* What went wrong:
A problem occurred evaluating root project 'kojisample'.
> Project with path ':configurations:postgres-reactive' could not be found in root project 'kojisample'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
[koji:kojisample]$ 
```
i used `compile "io.micronaut.configuration:postgres-reactive"`, then all is perfect!
